
import IndexPage from '@/views/IndexPage'

export default {
    routes:[
        {
            component:IndexPage,
            path:"/main",
            children:[
                {
                    path:"/main/addGov",
                    component:()=><p>新机构页面</p>
                },
                {
                    path:"/main/editGov/:id?",
                    component:()=><p>编辑机构</p>
                },
                {
                    path:"/main/govDetail/:id?",
                    component:()=><p>机构详情</p>
                },
                {
                    path:"/main/addPro",
                    component:()=><p>新建课程</p>
                },
                {
                    path:"/main/editPro/:id?",
                    component:()=><p>编辑课程</p>
                },
                {
                    path:"/main/proError",
                    component:()=><p>异常提示</p>
                },
                {
                    path:"/main/addClass",
                    component:()=><p>新建班级</p>
                },
                {
                    path:"/main/edrtClass/:id?",
                    component:()=><p>编辑班级</p>
                },
                {
                    path:"/main/classDetail/:id?",
                    component:()=><p>班级详情</p>
                },
                {
                    path:"/main/addStudent",
                    component:()=><p>新建学生</p>
                },
                {
                    path:"/main/edrtStudent/:id?",
                    component:()=><p>编辑学生</p>
                },
                {
                    path:"/main/management",
                    component:()=><p>报名处管理</p>
                },
                {
                    path:"/main/addLibrary",
                    component:()=><p>新增图管理</p>
                },
                {
                    path:"/main/erdtLibrary/:id",
                    component:()=><p>编辑图管理</p>
                },
                {
                    path:"/main/advertising",
                    component:()=><p>PC主站广告管理</p>
                },
                {
                    path:"/main/basic",
                    component:()=><p>基础管理</p>
                },
                {
                    path:"/main/account",
                    component:()=><p>账号管理</p>
                },
            ]
        },
        {
            path:"/",
            redirect:'/main/addGov'
        }
    ],
      pages:[
          {
            title:"机构管理",
            icon:"",
            children:[
                {
                    title:"新增机构",
                    path:"/main/addGov",

                    show:true
                },
                {
                    title:"编辑机构",
                    path:"/main/editGov/:id?",

                    show:false
                },
                {
                    title:"机构详情",
                    path:"/main/govDetail/:id?",
                    show:false
                }
            ]
        },
        {
            title:"教务管理",
            icon:"",
            children:[
                {
                    title:"课程管理",
                    children:[
                        {
                            title:"新建课程",
                            path:"/main/addPro",
                            show:true

                        },
                        {
                            title:"编辑课程",
                            path:"/main/editPro/:id?",
                            show:false
                        },
                        {
                            title:"异常提示",
                            path:"/main/proError",
                            show:false
                        }
                    ]
                },
                {
                    title:"班级管理",
                    children:[
                        {
                            title:"新建班级",
                            path:"/main/addClass",
                            show:true
                        },
                        {
                            title:"编辑班级",
                            path:"/main/edrtClass/:id?",
                            show:false
                        },
                        {
                            title:"班级详情",
                            path:"/main/classDetail/:id?",
                            show:false
                        }
                    ]
                },
                {
                    title:"学生管理",
                    children:[
                        {
                            title:"新建学生",
                            path:"/main/addStudent",
                            show:true
                        },
                        {
                            title:"编辑学生",
                            path:"/main/edrtStudent/:id?",
                            show:false
                        }
                    ]
                }
            
            ]
        },
        {
            title:"招生中心",
            icon:"",
            children:[
                {
                    title:"报名册管理",
                    path:"/main/management",
                    show:true
                }
            ]
        },
        {
            title:"运营管理",
            icon:"",
            children:[
                {
                    title:"APP bannner图管理",
                    children:[
                        {
                            title:"新增图管理",
                            path:"/main/addLibrary",
                            show:true
                        },
                        {
                            title:"编辑图管理",
                            path:"/main/erdtLibrary/:id?",
                            show:false
                        }
                    ]
                },
                {
                    title:"PC主站广告管理",
                    children:[]
                }
            ]
        },
        {
            title:"基础管理",
            icon:"",
            children:[]
        },
        {
            title:"账号管理",
           icon:"",
           children:[]
        }
    ]
}